substitutions:
  devicename: Mill Zero
  lower_devicename: "mill-zero"

esphome:
  name: "${lower_devicename}"
  friendly_name: "${devicename}"
  includes:
    - mill.h  

esp8266:
  board: esp01_1m

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: "iOV+NdOK8MmrbOEeXgBjLrKx2C9MMcI8LtJX7V0jJSw="

ota:
  password: "7996ed358c05351c408d91e520f79459"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${devicename} Fallback Hotspot"
    password: "uUA5fHxXU69J"

captive_portal:

uart:
  id: uart_1
  rx_pin: GPIO03
  tx_pin: GPIO01
  baud_rate: 9600

switch:
  - platform: gpio
    pin: GPIO02
    internal: true
    restore_mode: ALWAYS_ON
    name: "${devicename} GPIO"  

climate:
- platform: custom

  lambda: |-
    auto my_custom_climate = new MyCustomClimate(id(uart_1));
    App.register_component(my_custom_climate);
    return {my_custom_climate};


  climates:
    - name: "${devicename} Climate"
      visual:
         min_temperature: 5 °C
         max_temperature: 35 °C
         temperature_step: 1 °C    
